'use client'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Select } from '@/components/ui/select'
import { Textarea } from '@/components/ui/textarea'
import { useEditorStore } from '@/editor/store/editor-store'

const number = (value: number, onChange: (value: number) => void) => <Input type="number" value={Math.round(value)} onChange={(e)=>onChange(Number(e.target.value))}/>
const gradientPresets = {
  neutral: { type: 'linear-gradient' as const, angle: 135, alpha: 1, stops: [{ color: '#ffffff', position: 0, alpha: 1 }, { color: '#f5f5f5', position: 100, alpha: 1 }] },
  blue: { type: 'linear-gradient' as const, angle: 135, alpha: 1, stops: [{ color: '#eff6ff', position: 0, alpha: 1 }, { color: '#2563eb', position: 100, alpha: 0.75 }] },
  mist: { type: 'radial-gradient' as const, center: { x: 50, y: 35 }, radius: 75, alpha: 1, stops: [{ color: '#f5f3ff', position: 0, alpha: 1 }, { color: '#ffffff', position: 100, alpha: 1 }] },
}

export function PropertiesPanel() {
  const { activePage, selectedIds, project, updateSelected, createComponent, detachInstance } = useEditorStore()
  const node = selectedIds.length === 1 && activePage ? activePage.nodes[selectedIds[0]] : null
  if (!project || !activePage) return <aside className="w-80 border-l border-border bg-panel p-4"/>
  if (!node) return <aside className="w-[300px] overflow-auto border-l border-neutral-200 bg-white p-3 text-xs"><h2 className="font-semibold text-neutral-900">Page</h2><label className="mt-3 block text-neutral-600">Background<Input className="mt-1" type="color" value={activePage.backgroundColor} onChange={()=>{}}/></label><div className="mt-4 grid grid-cols-2 gap-2"><label className="flex items-center gap-2"><input type="checkbox" defaultChecked/> Grid</label><label className="flex items-center gap-2"><input type="checkbox" defaultChecked={project.settings.snapToGrid}/> Snap</label></div><h2 className="mt-6 font-semibold text-neutral-900">Tokens</h2>{Object.values(project.tokens).map((t)=><div key={t.id} className="mt-1.5 flex items-center justify-between rounded-lg border border-neutral-100 bg-neutral-50 px-2 py-1.5"><span>{t.name}</span><span>{t.type==='color'?t.value:t.value}</span></div>)}</aside>
  const fill = node.fills[0] ?? { type: 'solid' as const, color: '#ffffff', alpha: 1 }
  return <aside className="w-[300px] overflow-auto border-l border-neutral-200 bg-white p-3 text-xs text-neutral-700">
    <h2 className="font-semibold">Layer</h2>
    <label className="mt-3 block">Name<Input className="mt-1" value={node.name} onChange={(e)=>updateSelected({ name: e.target.value } as never)}/></label>
    <div className="mt-3 grid grid-cols-2 gap-2"><label>Visible<Select value={String(node.visible)} onChange={(e)=>updateSelected({ visible: e.target.value==='true' } as never)}><option value="true">Visible</option><option value="false">Hidden</option></Select></label><label>Locked<Select value={String(node.locked)} onChange={(e)=>updateSelected({ locked: e.target.value==='true' } as never)}><option value="false">Unlocked</option><option value="true">Locked</option></Select></label></div>
    <h2 className="mt-6 font-semibold">Position & Size</h2>
    <div className="mt-2 grid grid-cols-2 gap-2"><label>X{number(node.x,(x)=>updateSelected({x} as never))}</label><label>Y{number(node.y,(y)=>updateSelected({y} as never))}</label><label>W{number(node.width,(width)=>updateSelected({width} as never))}</label><label>H{number(node.height,(height)=>updateSelected({height} as never))}</label><label>Rotation{number(node.rotation,(rotation)=>updateSelected({rotation} as never))}</label><label>Opacity<Input type="number" min="0" max="1" step="0.05" value={node.opacity} onChange={(e)=>updateSelected({opacity:Number(e.target.value)} as never)}/></label></div>
    <h2 className="mt-6 font-semibold">Fill</h2>
    <label className="mt-2 block">Type<Select value={fill.type} onChange={(e)=>updateSelected({ fills: [e.target.value === 'solid' ? { type:'solid', color:'#ffffff', alpha:1 } : e.target.value === 'linear-gradient' ? gradientPresets.neutral : gradientPresets.mist] } as never)}><option value="solid">Solid</option><option value="linear-gradient">Linear gradient</option><option value="radial-gradient">Radial gradient</option></Select></label>
    {fill.type === 'solid' && <label className="mt-2 block">Color<Input type="color" value={fill.color} onChange={(e)=>updateSelected({ fills: [{ ...fill, color:e.target.value }] } as never)}/></label>}
    {fill.type === 'linear-gradient' && <div className="mt-2 space-y-2"><label>Angle{number(fill.angle,(angle)=>updateSelected({fills:[{...fill,angle}]} as never))}</label>{fill.stops.map((stop,index)=><div key={index} className="grid grid-cols-[1fr_64px] gap-2"><Input type="color" value={stop.color} onChange={(e)=>{ const stops=[...fill.stops]; stops[index]={...stop,color:e.target.value}; updateSelected({fills:[{...fill,stops}]} as never)}}/><Input type="number" value={stop.position} onChange={(e)=>{ const stops=[...fill.stops]; stops[index]={...stop,position:Number(e.target.value)}; updateSelected({fills:[{...fill,stops}]} as never)}}/></div>)}<div className="flex gap-2"><Button size="sm" onClick={()=>updateSelected({fills:[gradientPresets.blue]} as never)}>Blue</Button><Button size="sm" onClick={()=>updateSelected({fills:[gradientPresets.neutral]} as never)}>Neutral</Button></div></div>}
    {fill.type === 'radial-gradient' && <div className="mt-2 space-y-2"><label>Radius{number(fill.radius,(radius)=>updateSelected({fills:[{...fill,radius}]} as never))}</label><Button size="sm" onClick={()=>updateSelected({fills:[gradientPresets.mist]} as never)}>Purple mist</Button></div>}
    <h2 className="mt-6 font-semibold">Stroke & Radius</h2>
    <label className="mt-2 block">Radius{number(typeof node.cornerRadius === 'number' ? node.cornerRadius : 0, (cornerRadius)=>updateSelected({cornerRadius} as never))}</label>
    {(node.type === 'frame' || node.type === 'component') && <><h2 className="mt-6 font-semibold">Layout</h2><Select value={node.layout.mode} onChange={(e)=>updateSelected({ layout: { ...node.layout, mode: e.target.value } } as never)}><option value="none">None</option><option value="horizontal">Horizontal</option><option value="vertical">Vertical</option></Select><div className="mt-2 grid grid-cols-2 gap-2"><label>Gap{number(node.layout.gap,(gap)=>updateSelected({layout:{...node.layout,gap}} as never))}</label><label>Padding{number(node.layout.padding.top,(v)=>updateSelected({layout:{...node.layout,padding:{top:v,right:v,bottom:v,left:v}}} as never))}</label></div></>}
    {node.type === 'text' && <><h2 className="mt-6 font-semibold">Text</h2><Textarea value={node.text} onChange={(e)=>updateSelected({text:e.target.value} as never)}/><div className="mt-2 grid grid-cols-2 gap-2"><label>Font<Select value={node.fontFamily} onChange={(e)=>updateSelected({fontFamily:e.target.value} as never)}>{['Inter Variable','Inter','Arial','Helvetica','Georgia','Times New Roman','Monospace'].map(f=><option key={f}>{f}</option>)}</Select></label><label>Size{number(node.fontSize,(fontSize)=>updateSelected({fontSize} as never))}</label><label>Weight<Select value={node.fontWeight} onChange={(e)=>updateSelected({fontWeight:Number(e.target.value)} as never)}>{[300,400,500,600,700,800].map(w=><option key={w}>{w}</option>)}</Select></label><label>Color<Input type="color" value={node.color} onChange={(e)=>updateSelected({color:e.target.value} as never)}/></label></div></>}
    {node.type === 'image' && <><h2 className="mt-6 font-semibold">Image</h2><label>Alt text<Input value={node.alt} onChange={(e)=>updateSelected({alt:e.target.value} as never)}/></label><label className="mt-2 block">Object fit<Select value={node.objectFit} onChange={(e)=>updateSelected({objectFit:e.target.value} as never)}><option value="cover">Cover</option><option value="contain">Contain</option><option value="fill">Fill</option></Select></label></>}
    <div className="mt-6 flex flex-wrap gap-2"><Button size="sm" onClick={createComponent}>Create component</Button>{node.type==='instance' && <Button size="sm" onClick={detachInstance}>Detach</Button>}</div>
  </aside>
}
