import { expect, test } from '@playwright/test'

test('user can complete onboarding and open editor', async ({ page }) => {
  await page.goto('/onboarding')
  await Promise.all([page.waitForURL(/projects/), page.getByRole('button', { name: /finish/i }).click()])
  await expect(page.getByTitle('Select (V)')).toBeVisible()
  await expect(page.getByTitle('Rectangle (R)')).toBeVisible()
})

test('dashboard can create a project and switch theme settings', async ({ page }) => {
  await page.goto('/app')
  await Promise.all([page.waitForURL(/projects/), page.getByRole('button', { name: /new file/i }).click()])
  await expect(page.getByTitle('Frame (F)')).toBeVisible()
  await page.goto('/app/settings')
  await page.locator('select').first().selectOption('dark')
  await page.getByRole('button', { name: /save settings/i }).click()
  await expect(page.locator('html')).toHaveClass(/dark/)
})

test('editor can create nodes and undo redo', async ({ page }) => {
  await page.goto('/app')
  await Promise.all([page.waitForURL(/projects/), page.getByRole('button', { name: /new file/i }).click()])
  await page.getByTitle('Rectangle (R)').click()
  const createBox = await page.getByTestId('canvas').boundingBox()
  if (!createBox) throw new Error('Canvas not visible')
  await page.mouse.move(createBox.x + 500, createBox.y + 260)
  await page.mouse.down()
  await page.mouse.move(createBox.x + 660, createBox.y + 360, { steps: 4 })
  await page.mouse.up()
  await expect(page.getByText('Rectangle')).toBeVisible()
  const layout = page.locator('section').filter({ hasText: 'Layout' })
  const xBefore = Number(await layout.getByLabel('X', { exact: true }).inputValue())
  const canvasBox = await page.getByTestId('canvas').boundingBox()
  if (!canvasBox) throw new Error('Canvas not visible')
  await page.mouse.move(canvasBox.x + 552, canvasBox.y + 292)
  await page.mouse.down()
  await page.mouse.move(canvasBox.x + 592, canvasBox.y + 312, { steps: 5 })
  await page.mouse.up()
  const xAfter = Number(await layout.getByLabel('X', { exact: true }).inputValue())
  expect(xAfter - xBefore).toBeGreaterThanOrEqual(40)
  expect(xAfter - xBefore).toBeLessThanOrEqual(80)
  await page.keyboard.press(process.platform === 'darwin' ? 'Meta+Z' : 'Control+Z')
  await page.keyboard.press(process.platform === 'darwin' ? 'Meta+Shift+Z' : 'Control+Shift+Z')
  await expect(page.getByText('Rectangle')).toBeVisible()
})

test('editor supports zoom, context menu, and gradient fill', async ({ page }) => {
  await page.goto('/app')
  await Promise.all([page.waitForURL(/projects/), page.getByRole('button', { name: /new file/i }).click()])
  await page.getByTitle('Rectangle (R)').click()
  const canvasBox = await page.getByTestId('canvas').boundingBox()
  if (!canvasBox) throw new Error('Canvas not visible')
  await page.mouse.move(canvasBox.x + 520, canvasBox.y + 280)
  await page.mouse.down()
  await page.mouse.move(canvasBox.x + 680, canvasBox.y + 380, { steps: 4 })
  await page.mouse.up()
  await page.keyboard.down(process.platform === 'darwin' ? 'Meta' : 'Control')
  await page.mouse.wheel(0, -120)
  await page.keyboard.up(process.platform === 'darwin' ? 'Meta' : 'Control')
  await expect(page.getByText(/12[0-9]%/)).toBeVisible()
  await page.keyboard.press(process.platform === 'darwin' ? 'Meta+=' : 'Control+=')
  await page.getByRole('button', { name: 'Gradient' }).click()
  await expect(page.locator('section').filter({ hasText: 'Fill' }).getByLabel('∠')).toBeVisible()
})
