import { HugeiconsIcon, type IconSvgElement } from '@hugeicons/react'
import {
  Add01Icon,
  ArrangeIcon,
  ArrowDown01Icon,
  ArrowLeft01Icon,
  ArrowReloadHorizontalIcon,
  ArrowRight01Icon,
  ArrowTurnBackwardIcon,
  ArrowTurnForwardIcon,
  ComponentIcon,
  Copy01Icon,
  CursorPointer02Icon,
  CursorRectangleSelection01Icon,
  CursorTextIcon,
  Delete02Icon,
  Download01Icon,
  EyeIcon,
  GridIcon,
  GridViewIcon,
  HandGrabIcon,
  Image01Icon,
  Layers01Icon,
  LockIcon,
  Menu01Icon,
  Search01Icon,
  Settings01Icon,
  SquareIcon,
  TextIcon,
  UnavailableIcon,
} from '@hugeicons/core-free-icons'

export const icons = {
  add: Add01Icon,
  arrange: ArrangeIcon,
  back: ArrowLeft01Icon,
  chevronDown: ArrowDown01Icon,
  component: ComponentIcon,
  copy: Copy01Icon,
  cursor: CursorPointer02Icon,
  delete: Delete02Icon,
  download: Download01Icon,
  eye: EyeIcon,
  frame: CursorRectangleSelection01Icon,
  grid: GridIcon,
  hand: HandGrabIcon,
  image: Image01Icon,
  layers: Layers01Icon,
  list: GridViewIcon,
  lock: LockIcon,
  menu: Menu01Icon,
  redo: ArrowTurnForwardIcon,
  rectangle: SquareIcon,
  reload: ArrowReloadHorizontalIcon,
  search: Search01Icon,
  settings: Settings01Icon,
  text: TextIcon || CursorTextIcon,
  unavailable: UnavailableIcon,
  undo: ArrowTurnBackwardIcon,
  forward: ArrowRight01Icon,
}

export function Icon({ icon, size = 16, className }: { icon: IconSvgElement; size?: number; className?: string }) {
  return <HugeiconsIcon icon={icon} size={size} strokeWidth={1.8} className={className} />
}
